# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifestos', '0008_auto_20160503_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='collections',
            field=models.ManyToManyField(blank=True, to='manifestos.Collection'),
        ),
    ]
