# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_squashed_0003_auto_20160527_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='quote',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='range_end_offset',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='range_start_offset',
            field=models.BigIntegerField(),
        ),
    ]
